// Bundles samples/*.txt into lib/samples.js so the serverless function can seed
// demo workspaces without reading files at runtime.
import fs from 'node:fs';

const DEMO = [
  ['cloud-hosting.txt', 'Managed cloud hosting (Stratus Nine)', 'Customer'],
  ['crm-subscription.txt', 'CRM subscription (Helixa)', 'Customer'],
  ['office-lease.txt', 'Hitec City office licence', 'Licensee'],
  ['facility-services.txt', 'Facility management (Cleanline)', 'Client']
];

const samples = DEMO.map(([file, title, perspective]) => ({
  title,
  perspective,
  text: fs.readFileSync(new URL(`../samples/${file}`, import.meta.url), 'utf8').replace(/\r\n?/g, '\n')
}));

fs.writeFileSync(
  new URL('../lib/samples.js', import.meta.url),
  '// Generated by scripts/build-samples.js from samples/*.txt. Do not edit.\n' +
  `export const SAMPLES = ${JSON.stringify(samples, null, 2)};\n`
);
console.log(`wrote ${samples.length} samples`);
